package com.mvqa.demo.Mapper;

import com.mvqa.demo.model.po.ctInfoPo;
import com.mvqa.demo.model.po.ctInfoPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ctInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_information
     *
     * @mbggenerated
     */
    int deleteByExample(ctInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_information
     *
     * @mbggenerated
     */
    int insert(ctInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_information
     *
     * @mbggenerated
     */
    int insertSelective(ctInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_information
     *
     * @mbggenerated
     */
    List<ctInfoPo> selectByExample(ctInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_information
     *
     * @mbggenerated
     */
    ctInfoPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_information
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ctInfoPo record, @Param("example") ctInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_information
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ctInfoPo record, @Param("example") ctInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ctInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ctInfoPo record);
}