package com.mvqa.demo.Mapper;

import com.mvqa.demo.model.po.ctValPo;
import com.mvqa.demo.model.po.ctValPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ctValPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_validation
     *
     * @mbggenerated
     */
    int deleteByExample(ctValPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_validation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_validation
     *
     * @mbggenerated
     */
    int insert(ctValPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_validation
     *
     * @mbggenerated
     */
    int insertSelective(ctValPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_validation
     *
     * @mbggenerated
     */
    List<ctValPo> selectByExample(ctValPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_validation
     *
     * @mbggenerated
     */
    ctValPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_validation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ctValPo record, @Param("example") ctValPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_validation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ctValPo record, @Param("example") ctValPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_validation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ctValPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_validation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ctValPo record);
}