package com.mvqa.demo.Mapper;

import com.mvqa.demo.model.po.DatasetPo;
import com.mvqa.demo.model.po.DatasetPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DatasetPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataset
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataset
     *
     * @mbggenerated
     */
    int insert(DatasetPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataset
     *
     * @mbggenerated
     */
    int insertSelective(DatasetPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataset
     *
     * @mbggenerated
     */
    List<DatasetPo> selectByExample(DatasetPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataset
     *
     * @mbggenerated
     */
    DatasetPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataset
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DatasetPo record, @Param("example") DatasetPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataset
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DatasetPo record, @Param("example") DatasetPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataset
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DatasetPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataset
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DatasetPo record);
}