package com.mvqa.demo.Mapper;

import com.mvqa.demo.model.po.ReportPo;
import com.mvqa.demo.model.po.ReportPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    int insert(ReportPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    int insertSelective(ReportPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    List<ReportPo> selectByExample(ReportPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    ReportPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReportPo record, @Param("example") ReportPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReportPo record, @Param("example") ReportPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportPo record);
}