package com.mvqa.demo.model.po;

public class ctInfoPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_information.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_information.patient_id
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_information.sym
     *
     * @mbggenerated
     */
    private String sym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_information.photo_id
     *
     * @mbggenerated
     */
    private String photoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_information.dia_list
     *
     * @mbggenerated
     */
    private String diaList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_information.annotation
     *
     * @mbggenerated
     */
    private String annotation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_information.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_information.dataset
     *
     * @mbggenerated
     */
    private String dataset;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_information.id
     *
     * @return the value of ct_information.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_information.id
     *
     * @param id the value for ct_information.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_information.patient_id
     *
     * @return the value of ct_information.patient_id
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_information.patient_id
     *
     * @param patientId the value for ct_information.patient_id
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_information.sym
     *
     * @return the value of ct_information.sym
     *
     * @mbggenerated
     */
    public String getSym() {
        return sym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_information.sym
     *
     * @param sym the value for ct_information.sym
     *
     * @mbggenerated
     */
    public void setSym(String sym) {
        this.sym = sym == null ? null : sym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_information.photo_id
     *
     * @return the value of ct_information.photo_id
     *
     * @mbggenerated
     */
    public String getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_information.photo_id
     *
     * @param photoId the value for ct_information.photo_id
     *
     * @mbggenerated
     */
    public void setPhotoId(String photoId) {
        this.photoId = photoId == null ? null : photoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_information.dia_list
     *
     * @return the value of ct_information.dia_list
     *
     * @mbggenerated
     */
    public String getDiaList() {
        return diaList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_information.dia_list
     *
     * @param diaList the value for ct_information.dia_list
     *
     * @mbggenerated
     */
    public void setDiaList(String diaList) {
        this.diaList = diaList == null ? null : diaList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_information.annotation
     *
     * @return the value of ct_information.annotation
     *
     * @mbggenerated
     */
    public String getAnnotation() {
        return annotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_information.annotation
     *
     * @param annotation the value for ct_information.annotation
     *
     * @mbggenerated
     */
    public void setAnnotation(String annotation) {
        this.annotation = annotation == null ? null : annotation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_information.status
     *
     * @return the value of ct_information.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_information.status
     *
     * @param status the value for ct_information.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_information.dataset
     *
     * @return the value of ct_information.dataset
     *
     * @mbggenerated
     */
    public String getDataset() {
        return dataset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_information.dataset
     *
     * @param dataset the value for ct_information.dataset
     *
     * @mbggenerated
     */
    public void setDataset(String dataset) {
        this.dataset = dataset == null ? null : dataset.trim();
    }
}