package com.mvqa.demo.model.po;

public class ctValPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_validation.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_validation.patient_id
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_validation.photo_id
     *
     * @mbggenerated
     */
    private String photoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_validation.dia_list
     *
     * @mbggenerated
     */
    private String diaList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_validation.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_validation.bone_name
     *
     * @mbggenerated
     */
    private String boneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_validation.direction
     *
     * @mbggenerated
     */
    private String direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_validation.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_validation.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_validation.dataset
     *
     * @mbggenerated
     */
    private String dataset;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_validation.id
     *
     * @return the value of ct_validation.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_validation.id
     *
     * @param id the value for ct_validation.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_validation.patient_id
     *
     * @return the value of ct_validation.patient_id
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_validation.patient_id
     *
     * @param patientId the value for ct_validation.patient_id
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_validation.photo_id
     *
     * @return the value of ct_validation.photo_id
     *
     * @mbggenerated
     */
    public String getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_validation.photo_id
     *
     * @param photoId the value for ct_validation.photo_id
     *
     * @mbggenerated
     */
    public void setPhotoId(String photoId) {
        this.photoId = photoId == null ? null : photoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_validation.dia_list
     *
     * @return the value of ct_validation.dia_list
     *
     * @mbggenerated
     */
    public String getDiaList() {
        return diaList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_validation.dia_list
     *
     * @param diaList the value for ct_validation.dia_list
     *
     * @mbggenerated
     */
    public void setDiaList(String diaList) {
        this.diaList = diaList == null ? null : diaList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_validation.description
     *
     * @return the value of ct_validation.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_validation.description
     *
     * @param description the value for ct_validation.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_validation.bone_name
     *
     * @return the value of ct_validation.bone_name
     *
     * @mbggenerated
     */
    public String getBoneName() {
        return boneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_validation.bone_name
     *
     * @param boneName the value for ct_validation.bone_name
     *
     * @mbggenerated
     */
    public void setBoneName(String boneName) {
        this.boneName = boneName == null ? null : boneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_validation.direction
     *
     * @return the value of ct_validation.direction
     *
     * @mbggenerated
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_validation.direction
     *
     * @param direction the value for ct_validation.direction
     *
     * @mbggenerated
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_validation.type
     *
     * @return the value of ct_validation.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_validation.type
     *
     * @param type the value for ct_validation.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_validation.position
     *
     * @return the value of ct_validation.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_validation.position
     *
     * @param position the value for ct_validation.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_validation.dataset
     *
     * @return the value of ct_validation.dataset
     *
     * @mbggenerated
     */
    public String getDataset() {
        return dataset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_validation.dataset
     *
     * @param dataset the value for ct_validation.dataset
     *
     * @mbggenerated
     */
    public void setDataset(String dataset) {
        this.dataset = dataset == null ? null : dataset.trim();
    }
}