package com.mvqa.demo.model.po;

public class DatasetPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataset.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataset.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataset.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataset.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataset.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataset.islabeled
     *
     * @mbggenerated
     */
    private Integer islabeled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataset.test
     *
     * @mbggenerated
     */
    private Integer test;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataset.valid
     *
     * @mbggenerated
     */
    private Integer valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataset.train
     *
     * @mbggenerated
     */
    private Integer train;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataset.id
     *
     * @return the value of dataset.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataset.id
     *
     * @param id the value for dataset.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataset.name
     *
     * @return the value of dataset.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataset.name
     *
     * @param name the value for dataset.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataset.description
     *
     * @return the value of dataset.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataset.description
     *
     * @param description the value for dataset.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataset.status
     *
     * @return the value of dataset.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataset.status
     *
     * @param status the value for dataset.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataset.link
     *
     * @return the value of dataset.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataset.link
     *
     * @param link the value for dataset.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataset.islabeled
     *
     * @return the value of dataset.islabeled
     *
     * @mbggenerated
     */
    public Integer getIslabeled() {
        return islabeled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataset.islabeled
     *
     * @param islabeled the value for dataset.islabeled
     *
     * @mbggenerated
     */
    public void setIslabeled(Integer islabeled) {
        this.islabeled = islabeled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataset.test
     *
     * @return the value of dataset.test
     *
     * @mbggenerated
     */
    public Integer getTest() {
        return test;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataset.test
     *
     * @param test the value for dataset.test
     *
     * @mbggenerated
     */
    public void setTest(Integer test) {
        this.test = test;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataset.valid
     *
     * @return the value of dataset.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataset.valid
     *
     * @param valid the value for dataset.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataset.train
     *
     * @return the value of dataset.train
     *
     * @mbggenerated
     */
    public Integer getTrain() {
        return train;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataset.train
     *
     * @param train the value for dataset.train
     *
     * @mbggenerated
     */
    public void setTrain(Integer train) {
        this.train = train;
    }
}