package com.mvqa.demo.model.po;

import java.util.Date;

public class ReportPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.data
     *
     * @mbggenerated
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.savepath
     *
     * @mbggenerated
     */
    private String savepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.prec
     *
     * @mbggenerated
     */
    private Integer prec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.recall
     *
     * @mbggenerated
     */
    private Integer recall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.f1
     *
     * @mbggenerated
     */
    private Integer f1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.classification
     *
     * @mbggenerated
     */
    private String classification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.epoch
     *
     * @mbggenerated
     */
    private Integer epoch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.batchsize
     *
     * @mbggenerated
     */
    private Integer batchsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.rnn_cell
     *
     * @mbggenerated
     */
    private String rnnCell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.embedding
     *
     * @mbggenerated
     */
    private String embedding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.bleu
     *
     * @mbggenerated
     */
    private Float bleu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.id
     *
     * @return the value of report.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.id
     *
     * @param id the value for report.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.name
     *
     * @return the value of report.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.name
     *
     * @param name the value for report.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.date
     *
     * @return the value of report.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.date
     *
     * @param date the value for report.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.state
     *
     * @return the value of report.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.state
     *
     * @param state the value for report.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.data
     *
     * @return the value of report.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.data
     *
     * @param data the value for report.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.savepath
     *
     * @return the value of report.savepath
     *
     * @mbggenerated
     */
    public String getSavepath() {
        return savepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.savepath
     *
     * @param savepath the value for report.savepath
     *
     * @mbggenerated
     */
    public void setSavepath(String savepath) {
        this.savepath = savepath == null ? null : savepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.prec
     *
     * @return the value of report.prec
     *
     * @mbggenerated
     */
    public Integer getPrec() {
        return prec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.prec
     *
     * @param prec the value for report.prec
     *
     * @mbggenerated
     */
    public void setPrec(Integer prec) {
        this.prec = prec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.recall
     *
     * @return the value of report.recall
     *
     * @mbggenerated
     */
    public Integer getRecall() {
        return recall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.recall
     *
     * @param recall the value for report.recall
     *
     * @mbggenerated
     */
    public void setRecall(Integer recall) {
        this.recall = recall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.f1
     *
     * @return the value of report.f1
     *
     * @mbggenerated
     */
    public Integer getF1() {
        return f1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.f1
     *
     * @param f1 the value for report.f1
     *
     * @mbggenerated
     */
    public void setF1(Integer f1) {
        this.f1 = f1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.classification
     *
     * @return the value of report.classification
     *
     * @mbggenerated
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.classification
     *
     * @param classification the value for report.classification
     *
     * @mbggenerated
     */
    public void setClassification(String classification) {
        this.classification = classification == null ? null : classification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.epoch
     *
     * @return the value of report.epoch
     *
     * @mbggenerated
     */
    public Integer getEpoch() {
        return epoch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.epoch
     *
     * @param epoch the value for report.epoch
     *
     * @mbggenerated
     */
    public void setEpoch(Integer epoch) {
        this.epoch = epoch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.batchsize
     *
     * @return the value of report.batchsize
     *
     * @mbggenerated
     */
    public Integer getBatchsize() {
        return batchsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.batchsize
     *
     * @param batchsize the value for report.batchsize
     *
     * @mbggenerated
     */
    public void setBatchsize(Integer batchsize) {
        this.batchsize = batchsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.rnn_cell
     *
     * @return the value of report.rnn_cell
     *
     * @mbggenerated
     */
    public String getRnnCell() {
        return rnnCell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.rnn_cell
     *
     * @param rnnCell the value for report.rnn_cell
     *
     * @mbggenerated
     */
    public void setRnnCell(String rnnCell) {
        this.rnnCell = rnnCell == null ? null : rnnCell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.embedding
     *
     * @return the value of report.embedding
     *
     * @mbggenerated
     */
    public String getEmbedding() {
        return embedding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.embedding
     *
     * @param embedding the value for report.embedding
     *
     * @mbggenerated
     */
    public void setEmbedding(String embedding) {
        this.embedding = embedding == null ? null : embedding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.bleu
     *
     * @return the value of report.bleu
     *
     * @mbggenerated
     */
    public Float getBleu() {
        return bleu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.bleu
     *
     * @param bleu the value for report.bleu
     *
     * @mbggenerated
     */
    public void setBleu(Float bleu) {
        this.bleu = bleu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.deleted
     *
     * @return the value of report.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.deleted
     *
     * @param deleted the value for report.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}