package com.mvqa.demo.model.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ReportPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    public ReportPoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterionForJDBCDate("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterionForJDBCDate("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterionForJDBCDate("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterionForJDBCDate("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andDataIsNull() {
            addCriterion("data is null");
            return (Criteria) this;
        }

        public Criteria andDataIsNotNull() {
            addCriterion("data is not null");
            return (Criteria) this;
        }

        public Criteria andDataEqualTo(String value) {
            addCriterion("data =", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotEqualTo(String value) {
            addCriterion("data <>", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataGreaterThan(String value) {
            addCriterion("data >", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataGreaterThanOrEqualTo(String value) {
            addCriterion("data >=", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataLessThan(String value) {
            addCriterion("data <", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataLessThanOrEqualTo(String value) {
            addCriterion("data <=", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataLike(String value) {
            addCriterion("data like", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotLike(String value) {
            addCriterion("data not like", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataIn(List<String> values) {
            addCriterion("data in", values, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotIn(List<String> values) {
            addCriterion("data not in", values, "data");
            return (Criteria) this;
        }

        public Criteria andDataBetween(String value1, String value2) {
            addCriterion("data between", value1, value2, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotBetween(String value1, String value2) {
            addCriterion("data not between", value1, value2, "data");
            return (Criteria) this;
        }

        public Criteria andSavepathIsNull() {
            addCriterion("savepath is null");
            return (Criteria) this;
        }

        public Criteria andSavepathIsNotNull() {
            addCriterion("savepath is not null");
            return (Criteria) this;
        }

        public Criteria andSavepathEqualTo(String value) {
            addCriterion("savepath =", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathNotEqualTo(String value) {
            addCriterion("savepath <>", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathGreaterThan(String value) {
            addCriterion("savepath >", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathGreaterThanOrEqualTo(String value) {
            addCriterion("savepath >=", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathLessThan(String value) {
            addCriterion("savepath <", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathLessThanOrEqualTo(String value) {
            addCriterion("savepath <=", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathLike(String value) {
            addCriterion("savepath like", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathNotLike(String value) {
            addCriterion("savepath not like", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathIn(List<String> values) {
            addCriterion("savepath in", values, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathNotIn(List<String> values) {
            addCriterion("savepath not in", values, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathBetween(String value1, String value2) {
            addCriterion("savepath between", value1, value2, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathNotBetween(String value1, String value2) {
            addCriterion("savepath not between", value1, value2, "savepath");
            return (Criteria) this;
        }

        public Criteria andPrecIsNull() {
            addCriterion("prec is null");
            return (Criteria) this;
        }

        public Criteria andPrecIsNotNull() {
            addCriterion("prec is not null");
            return (Criteria) this;
        }

        public Criteria andPrecEqualTo(Integer value) {
            addCriterion("prec =", value, "prec");
            return (Criteria) this;
        }

        public Criteria andPrecNotEqualTo(Integer value) {
            addCriterion("prec <>", value, "prec");
            return (Criteria) this;
        }

        public Criteria andPrecGreaterThan(Integer value) {
            addCriterion("prec >", value, "prec");
            return (Criteria) this;
        }

        public Criteria andPrecGreaterThanOrEqualTo(Integer value) {
            addCriterion("prec >=", value, "prec");
            return (Criteria) this;
        }

        public Criteria andPrecLessThan(Integer value) {
            addCriterion("prec <", value, "prec");
            return (Criteria) this;
        }

        public Criteria andPrecLessThanOrEqualTo(Integer value) {
            addCriterion("prec <=", value, "prec");
            return (Criteria) this;
        }

        public Criteria andPrecIn(List<Integer> values) {
            addCriterion("prec in", values, "prec");
            return (Criteria) this;
        }

        public Criteria andPrecNotIn(List<Integer> values) {
            addCriterion("prec not in", values, "prec");
            return (Criteria) this;
        }

        public Criteria andPrecBetween(Integer value1, Integer value2) {
            addCriterion("prec between", value1, value2, "prec");
            return (Criteria) this;
        }

        public Criteria andPrecNotBetween(Integer value1, Integer value2) {
            addCriterion("prec not between", value1, value2, "prec");
            return (Criteria) this;
        }

        public Criteria andRecallIsNull() {
            addCriterion("recall is null");
            return (Criteria) this;
        }

        public Criteria andRecallIsNotNull() {
            addCriterion("recall is not null");
            return (Criteria) this;
        }

        public Criteria andRecallEqualTo(Integer value) {
            addCriterion("recall =", value, "recall");
            return (Criteria) this;
        }

        public Criteria andRecallNotEqualTo(Integer value) {
            addCriterion("recall <>", value, "recall");
            return (Criteria) this;
        }

        public Criteria andRecallGreaterThan(Integer value) {
            addCriterion("recall >", value, "recall");
            return (Criteria) this;
        }

        public Criteria andRecallGreaterThanOrEqualTo(Integer value) {
            addCriterion("recall >=", value, "recall");
            return (Criteria) this;
        }

        public Criteria andRecallLessThan(Integer value) {
            addCriterion("recall <", value, "recall");
            return (Criteria) this;
        }

        public Criteria andRecallLessThanOrEqualTo(Integer value) {
            addCriterion("recall <=", value, "recall");
            return (Criteria) this;
        }

        public Criteria andRecallIn(List<Integer> values) {
            addCriterion("recall in", values, "recall");
            return (Criteria) this;
        }

        public Criteria andRecallNotIn(List<Integer> values) {
            addCriterion("recall not in", values, "recall");
            return (Criteria) this;
        }

        public Criteria andRecallBetween(Integer value1, Integer value2) {
            addCriterion("recall between", value1, value2, "recall");
            return (Criteria) this;
        }

        public Criteria andRecallNotBetween(Integer value1, Integer value2) {
            addCriterion("recall not between", value1, value2, "recall");
            return (Criteria) this;
        }

        public Criteria andF1IsNull() {
            addCriterion("f1 is null");
            return (Criteria) this;
        }

        public Criteria andF1IsNotNull() {
            addCriterion("f1 is not null");
            return (Criteria) this;
        }

        public Criteria andF1EqualTo(Integer value) {
            addCriterion("f1 =", value, "f1");
            return (Criteria) this;
        }

        public Criteria andF1NotEqualTo(Integer value) {
            addCriterion("f1 <>", value, "f1");
            return (Criteria) this;
        }

        public Criteria andF1GreaterThan(Integer value) {
            addCriterion("f1 >", value, "f1");
            return (Criteria) this;
        }

        public Criteria andF1GreaterThanOrEqualTo(Integer value) {
            addCriterion("f1 >=", value, "f1");
            return (Criteria) this;
        }

        public Criteria andF1LessThan(Integer value) {
            addCriterion("f1 <", value, "f1");
            return (Criteria) this;
        }

        public Criteria andF1LessThanOrEqualTo(Integer value) {
            addCriterion("f1 <=", value, "f1");
            return (Criteria) this;
        }

        public Criteria andF1In(List<Integer> values) {
            addCriterion("f1 in", values, "f1");
            return (Criteria) this;
        }

        public Criteria andF1NotIn(List<Integer> values) {
            addCriterion("f1 not in", values, "f1");
            return (Criteria) this;
        }

        public Criteria andF1Between(Integer value1, Integer value2) {
            addCriterion("f1 between", value1, value2, "f1");
            return (Criteria) this;
        }

        public Criteria andF1NotBetween(Integer value1, Integer value2) {
            addCriterion("f1 not between", value1, value2, "f1");
            return (Criteria) this;
        }

        public Criteria andClassificationIsNull() {
            addCriterion("classification is null");
            return (Criteria) this;
        }

        public Criteria andClassificationIsNotNull() {
            addCriterion("classification is not null");
            return (Criteria) this;
        }

        public Criteria andClassificationEqualTo(String value) {
            addCriterion("classification =", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationNotEqualTo(String value) {
            addCriterion("classification <>", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationGreaterThan(String value) {
            addCriterion("classification >", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationGreaterThanOrEqualTo(String value) {
            addCriterion("classification >=", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationLessThan(String value) {
            addCriterion("classification <", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationLessThanOrEqualTo(String value) {
            addCriterion("classification <=", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationLike(String value) {
            addCriterion("classification like", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationNotLike(String value) {
            addCriterion("classification not like", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationIn(List<String> values) {
            addCriterion("classification in", values, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationNotIn(List<String> values) {
            addCriterion("classification not in", values, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationBetween(String value1, String value2) {
            addCriterion("classification between", value1, value2, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationNotBetween(String value1, String value2) {
            addCriterion("classification not between", value1, value2, "classification");
            return (Criteria) this;
        }

        public Criteria andEpochIsNull() {
            addCriterion("epoch is null");
            return (Criteria) this;
        }

        public Criteria andEpochIsNotNull() {
            addCriterion("epoch is not null");
            return (Criteria) this;
        }

        public Criteria andEpochEqualTo(Integer value) {
            addCriterion("epoch =", value, "epoch");
            return (Criteria) this;
        }

        public Criteria andEpochNotEqualTo(Integer value) {
            addCriterion("epoch <>", value, "epoch");
            return (Criteria) this;
        }

        public Criteria andEpochGreaterThan(Integer value) {
            addCriterion("epoch >", value, "epoch");
            return (Criteria) this;
        }

        public Criteria andEpochGreaterThanOrEqualTo(Integer value) {
            addCriterion("epoch >=", value, "epoch");
            return (Criteria) this;
        }

        public Criteria andEpochLessThan(Integer value) {
            addCriterion("epoch <", value, "epoch");
            return (Criteria) this;
        }

        public Criteria andEpochLessThanOrEqualTo(Integer value) {
            addCriterion("epoch <=", value, "epoch");
            return (Criteria) this;
        }

        public Criteria andEpochIn(List<Integer> values) {
            addCriterion("epoch in", values, "epoch");
            return (Criteria) this;
        }

        public Criteria andEpochNotIn(List<Integer> values) {
            addCriterion("epoch not in", values, "epoch");
            return (Criteria) this;
        }

        public Criteria andEpochBetween(Integer value1, Integer value2) {
            addCriterion("epoch between", value1, value2, "epoch");
            return (Criteria) this;
        }

        public Criteria andEpochNotBetween(Integer value1, Integer value2) {
            addCriterion("epoch not between", value1, value2, "epoch");
            return (Criteria) this;
        }

        public Criteria andBatchsizeIsNull() {
            addCriterion("batchsize is null");
            return (Criteria) this;
        }

        public Criteria andBatchsizeIsNotNull() {
            addCriterion("batchsize is not null");
            return (Criteria) this;
        }

        public Criteria andBatchsizeEqualTo(Integer value) {
            addCriterion("batchsize =", value, "batchsize");
            return (Criteria) this;
        }

        public Criteria andBatchsizeNotEqualTo(Integer value) {
            addCriterion("batchsize <>", value, "batchsize");
            return (Criteria) this;
        }

        public Criteria andBatchsizeGreaterThan(Integer value) {
            addCriterion("batchsize >", value, "batchsize");
            return (Criteria) this;
        }

        public Criteria andBatchsizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("batchsize >=", value, "batchsize");
            return (Criteria) this;
        }

        public Criteria andBatchsizeLessThan(Integer value) {
            addCriterion("batchsize <", value, "batchsize");
            return (Criteria) this;
        }

        public Criteria andBatchsizeLessThanOrEqualTo(Integer value) {
            addCriterion("batchsize <=", value, "batchsize");
            return (Criteria) this;
        }

        public Criteria andBatchsizeIn(List<Integer> values) {
            addCriterion("batchsize in", values, "batchsize");
            return (Criteria) this;
        }

        public Criteria andBatchsizeNotIn(List<Integer> values) {
            addCriterion("batchsize not in", values, "batchsize");
            return (Criteria) this;
        }

        public Criteria andBatchsizeBetween(Integer value1, Integer value2) {
            addCriterion("batchsize between", value1, value2, "batchsize");
            return (Criteria) this;
        }

        public Criteria andBatchsizeNotBetween(Integer value1, Integer value2) {
            addCriterion("batchsize not between", value1, value2, "batchsize");
            return (Criteria) this;
        }

        public Criteria andRnnCellIsNull() {
            addCriterion("rnn_cell is null");
            return (Criteria) this;
        }

        public Criteria andRnnCellIsNotNull() {
            addCriterion("rnn_cell is not null");
            return (Criteria) this;
        }

        public Criteria andRnnCellEqualTo(String value) {
            addCriterion("rnn_cell =", value, "rnnCell");
            return (Criteria) this;
        }

        public Criteria andRnnCellNotEqualTo(String value) {
            addCriterion("rnn_cell <>", value, "rnnCell");
            return (Criteria) this;
        }

        public Criteria andRnnCellGreaterThan(String value) {
            addCriterion("rnn_cell >", value, "rnnCell");
            return (Criteria) this;
        }

        public Criteria andRnnCellGreaterThanOrEqualTo(String value) {
            addCriterion("rnn_cell >=", value, "rnnCell");
            return (Criteria) this;
        }

        public Criteria andRnnCellLessThan(String value) {
            addCriterion("rnn_cell <", value, "rnnCell");
            return (Criteria) this;
        }

        public Criteria andRnnCellLessThanOrEqualTo(String value) {
            addCriterion("rnn_cell <=", value, "rnnCell");
            return (Criteria) this;
        }

        public Criteria andRnnCellLike(String value) {
            addCriterion("rnn_cell like", value, "rnnCell");
            return (Criteria) this;
        }

        public Criteria andRnnCellNotLike(String value) {
            addCriterion("rnn_cell not like", value, "rnnCell");
            return (Criteria) this;
        }

        public Criteria andRnnCellIn(List<String> values) {
            addCriterion("rnn_cell in", values, "rnnCell");
            return (Criteria) this;
        }

        public Criteria andRnnCellNotIn(List<String> values) {
            addCriterion("rnn_cell not in", values, "rnnCell");
            return (Criteria) this;
        }

        public Criteria andRnnCellBetween(String value1, String value2) {
            addCriterion("rnn_cell between", value1, value2, "rnnCell");
            return (Criteria) this;
        }

        public Criteria andRnnCellNotBetween(String value1, String value2) {
            addCriterion("rnn_cell not between", value1, value2, "rnnCell");
            return (Criteria) this;
        }

        public Criteria andEmbeddingIsNull() {
            addCriterion("embedding is null");
            return (Criteria) this;
        }

        public Criteria andEmbeddingIsNotNull() {
            addCriterion("embedding is not null");
            return (Criteria) this;
        }

        public Criteria andEmbeddingEqualTo(String value) {
            addCriterion("embedding =", value, "embedding");
            return (Criteria) this;
        }

        public Criteria andEmbeddingNotEqualTo(String value) {
            addCriterion("embedding <>", value, "embedding");
            return (Criteria) this;
        }

        public Criteria andEmbeddingGreaterThan(String value) {
            addCriterion("embedding >", value, "embedding");
            return (Criteria) this;
        }

        public Criteria andEmbeddingGreaterThanOrEqualTo(String value) {
            addCriterion("embedding >=", value, "embedding");
            return (Criteria) this;
        }

        public Criteria andEmbeddingLessThan(String value) {
            addCriterion("embedding <", value, "embedding");
            return (Criteria) this;
        }

        public Criteria andEmbeddingLessThanOrEqualTo(String value) {
            addCriterion("embedding <=", value, "embedding");
            return (Criteria) this;
        }

        public Criteria andEmbeddingLike(String value) {
            addCriterion("embedding like", value, "embedding");
            return (Criteria) this;
        }

        public Criteria andEmbeddingNotLike(String value) {
            addCriterion("embedding not like", value, "embedding");
            return (Criteria) this;
        }

        public Criteria andEmbeddingIn(List<String> values) {
            addCriterion("embedding in", values, "embedding");
            return (Criteria) this;
        }

        public Criteria andEmbeddingNotIn(List<String> values) {
            addCriterion("embedding not in", values, "embedding");
            return (Criteria) this;
        }

        public Criteria andEmbeddingBetween(String value1, String value2) {
            addCriterion("embedding between", value1, value2, "embedding");
            return (Criteria) this;
        }

        public Criteria andEmbeddingNotBetween(String value1, String value2) {
            addCriterion("embedding not between", value1, value2, "embedding");
            return (Criteria) this;
        }

        public Criteria andBleuIsNull() {
            addCriterion("bleu is null");
            return (Criteria) this;
        }

        public Criteria andBleuIsNotNull() {
            addCriterion("bleu is not null");
            return (Criteria) this;
        }

        public Criteria andBleuEqualTo(Float value) {
            addCriterion("bleu =", value, "bleu");
            return (Criteria) this;
        }

        public Criteria andBleuNotEqualTo(Float value) {
            addCriterion("bleu <>", value, "bleu");
            return (Criteria) this;
        }

        public Criteria andBleuGreaterThan(Float value) {
            addCriterion("bleu >", value, "bleu");
            return (Criteria) this;
        }

        public Criteria andBleuGreaterThanOrEqualTo(Float value) {
            addCriterion("bleu >=", value, "bleu");
            return (Criteria) this;
        }

        public Criteria andBleuLessThan(Float value) {
            addCriterion("bleu <", value, "bleu");
            return (Criteria) this;
        }

        public Criteria andBleuLessThanOrEqualTo(Float value) {
            addCriterion("bleu <=", value, "bleu");
            return (Criteria) this;
        }

        public Criteria andBleuIn(List<Float> values) {
            addCriterion("bleu in", values, "bleu");
            return (Criteria) this;
        }

        public Criteria andBleuNotIn(List<Float> values) {
            addCriterion("bleu not in", values, "bleu");
            return (Criteria) this;
        }

        public Criteria andBleuBetween(Float value1, Float value2) {
            addCriterion("bleu between", value1, value2, "bleu");
            return (Criteria) this;
        }

        public Criteria andBleuNotBetween(Float value1, Float value2) {
            addCriterion("bleu not between", value1, value2, "bleu");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(String value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(String value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(String value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(String value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(String value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLike(String value) {
            addCriterion("deleted like", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotLike(String value) {
            addCriterion("deleted not like", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<String> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<String> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(String value1, String value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(String value1, String value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andAttentionIsNull() {
            addCriterion("attention is null");
            return (Criteria) this;
        }

        public Criteria andAttentionIsNotNull() {
            addCriterion("attention is not null");
            return (Criteria) this;
        }

        public Criteria andAttentionEqualTo(String value) {
            addCriterion("attention =", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionNotEqualTo(String value) {
            addCriterion("attention <>", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionGreaterThan(String value) {
            addCriterion("attention >", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionGreaterThanOrEqualTo(String value) {
            addCriterion("attention >=", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionLessThan(String value) {
            addCriterion("attention <", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionLessThanOrEqualTo(String value) {
            addCriterion("attention <=", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionLike(String value) {
            addCriterion("attention like", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionNotLike(String value) {
            addCriterion("attention not like", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionIn(List<String> values) {
            addCriterion("attention in", values, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionNotIn(List<String> values) {
            addCriterion("attention not in", values, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionBetween(String value1, String value2) {
            addCriterion("attention between", value1, value2, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionNotBetween(String value1, String value2) {
            addCriterion("attention not between", value1, value2, "attention");
            return (Criteria) this;
        }

        public Criteria andConstructorIsNull() {
            addCriterion("constructor is null");
            return (Criteria) this;
        }

        public Criteria andConstructorIsNotNull() {
            addCriterion("constructor is not null");
            return (Criteria) this;
        }

        public Criteria andConstructorEqualTo(String value) {
            addCriterion("constructor =", value, "constructor");
            return (Criteria) this;
        }

        public Criteria andConstructorNotEqualTo(String value) {
            addCriterion("constructor <>", value, "constructor");
            return (Criteria) this;
        }

        public Criteria andConstructorGreaterThan(String value) {
            addCriterion("constructor >", value, "constructor");
            return (Criteria) this;
        }

        public Criteria andConstructorGreaterThanOrEqualTo(String value) {
            addCriterion("constructor >=", value, "constructor");
            return (Criteria) this;
        }

        public Criteria andConstructorLessThan(String value) {
            addCriterion("constructor <", value, "constructor");
            return (Criteria) this;
        }

        public Criteria andConstructorLessThanOrEqualTo(String value) {
            addCriterion("constructor <=", value, "constructor");
            return (Criteria) this;
        }

        public Criteria andConstructorLike(String value) {
            addCriterion("constructor like", value, "constructor");
            return (Criteria) this;
        }

        public Criteria andConstructorNotLike(String value) {
            addCriterion("constructor not like", value, "constructor");
            return (Criteria) this;
        }

        public Criteria andConstructorIn(List<String> values) {
            addCriterion("constructor in", values, "constructor");
            return (Criteria) this;
        }

        public Criteria andConstructorNotIn(List<String> values) {
            addCriterion("constructor not in", values, "constructor");
            return (Criteria) this;
        }

        public Criteria andConstructorBetween(String value1, String value2) {
            addCriterion("constructor between", value1, value2, "constructor");
            return (Criteria) this;
        }

        public Criteria andConstructorNotBetween(String value1, String value2) {
            addCriterion("constructor not between", value1, value2, "constructor");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}